version: "3.9"

services:

  db:
    container_name: postgres_db
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - stack   
    env_file:
      - .env

  backend:
    container_name: FastAPI_web
    depends_on:
      - db
    restart: always
    volumes:
      - web-media:/app/media
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - stack
    env_file:
      - .env

  migrations:
    depends_on:
      - db
    networks:
      - stack
    build:
      context: .
    entrypoint: "alembic upgrade head"
    env_file:
      - .env

  nginx:
    image: nginx
    volumes:
      - web-media:/media
    configs:
      - source: nginx.conf
        target: /etc/nginx/nginx.conf
    ports:
      - "443:443"
    networks:
      - stack
    depends_on:
      - db
      - backend

configs:
  nginx.conf:
    file: ./src/config/nginx.conf

volumes:
  postgres_data:
  web-media:

networks:
  stack:
