""" 

Revision ID: 024fc116cd74
Revises: 14381fbeec0f
Create Date: 2023-04-24 14:08:31.390010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024fc116cd74'
down_revision = '14381fbeec0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
